<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:p1="http://sap.com/xi/BASIS" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" name="BusinessComponentIn" targetNamespace="http://sap.com/xi/BASIS">
  <wsdl:documentation/>
  <wsp:UsingPolicy wsdl:required="true"/>
  <ifw:properties xmlns:ifw="urn:com-sap:ifr:v2:wsdl">
    <ifw:category>ifmmessif</ifw:category>
    <ifw:VersionID>517f0441c34511dbb5300017a44cb001</ifw:VersionID>
    <ifw:lifeCycleInfo>
      <objectState/>
      <objectstatus value="A"/>
      <personresponsible value="sap"/>
      <changed by="sap" on="1172242442437"/>
    </ifw:lifeCycleInfo>
    <ifw:runtimeVersion uri="urn:sap-com:soap:application:esr:server:710"/>
    <ifw:communicationProfile uri="prf_dt_if_com_stateless"/>
    <ifw:securityProfile uri="prf_dt_if_sec_low"/>
    <ifw:interfacePattern p2p="false">L</ifw:interfacePattern>
    <ifw:isSensitiveData>false</ifw:isSensitiveData>
    <ifw:classifications>
      <ifw:classification name="ObjectType" namespace="http://uddi.sap.com/classification" uddikey="uddi:uddi.sap.com:categorization:object-type" valueCode="ifmmessif"/>
      <ifw:classification name="ObjectID" namespace="http://uddi.sap.com/classification" uddikey="uddi:uddi.sap.com:categorization:object-id" valueCode="978e706090bc380da2e3ddd1c4afa409"/>
    </ifw:classifications>
    <ifw:additionalAttributes/>
    <ifw:methods>
      <ifw:method name="Check">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
      <ifw:method name="Change">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
      <ifw:method name="Query">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
      <ifw:method name="Create">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
      <ifw:method name="Revert">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
      <ifw:method name="Read">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
      <ifw:method name="Delete">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
      <ifw:method name="OpenForEdit">
        <ifw:isSynchron>true</ifw:isSynchron>
        <ifw:isIdempotent>false</ifw:isIdempotent>
        <ifw:isInbound>true</ifw:isInbound>
        <ifw:interfaceCategory>inbound</ifw:interfaceCategory>
        <ifw:communicationProfile uri="prf_dt_op_com_sync"/>
        <ifw:lifeCycleInfo>
          <objectState>N</objectState>
        </ifw:lifeCycleInfo>
        <ifw:contextobjects/>
      </ifw:method>
    </ifw:methods>
    <ifw:messages>
      <ifw:message name="BusinessComponentQueryResponse">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentQueryResponse</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>1068aa80807711dba7b10011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentQueryOut" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentQueryOut~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="LogMessageCollection">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">LogMessageCollection</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>fda002e0807611dbb29a0011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="LogMessageCollection" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=LogMessageCollection~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentQueryRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentQueryRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>11334d80807711dbb98c0011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentQueryIn" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentQueryIn~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="ConfigurationObjectModifyResponse">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">ConfigurationObjectModifyResponse</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>ffc92470807611dbbd600011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="ConfigurationObjectModifyOut" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=ConfigurationObjectModifyOut~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentOpenForEditResponse">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentOpenForEditResponse</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>10a69de0807711dbb1cc0011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentOpenForEditOut" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentOpenForEditOut~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentCreateRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentCreateRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>12a728d0807711dbcef00011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentCreateChangeIn" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentCreateChangeIn~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentChangeRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentChangeRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>11086cf0807711db9d0a0011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentCreateChangeIn" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentCreateChangeIn~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentReadRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentReadRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>132a6290807711db92c80011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentReadIn" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentReadIn~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentDeleteRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentDeleteRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>11da3be0807711dbcce20011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentDeleteOpenForEditIn" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentDeleteOpenForEditIn~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentOpenForEditRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentOpenForEditRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>10c0dca0807711dbcce80011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentDeleteOpenForEditIn" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentDeleteOpenForEditIn~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentCheckRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentCheckRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>1209d760807711db8fbe0011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentIdentifierCollection" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentIdentifierCollection~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentRevertRequest">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentRevertRequest</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>7f856170a70e11db803d001321070899</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentIdentifierCollection" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentIdentifierCollection~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
      <ifw:message name="BusinessComponentReadResponse">
        <ifw:messType>ifmmessage</ifw:messType>
        <ifw:keyElements>
          <ifw:elem id="NAME">BusinessComponentReadResponse</ifw:elem>
          <ifw:elem id="NAMESPACE">http://sap.com/xi/BASIS</ifw:elem>
        </ifw:keyElements>
        <ifw:technicalNamespace>http://sap.com/xi/BASIS</ifw:technicalNamespace>
        <ifw:VersionID>118453b0807711dbaa840011857d65de</ifw:VersionID>
        <ifw:xmlNamespace>http://sap.com/xi/BASIS</ifw:xmlNamespace>
        <ifw:dataType name="BusinessComponentReadOut" namespace="http://sap.com/xi/BASIS" swcvId="c90d3621a40a11e18645d49f0a4290b1" uri="name=BusinessComponentReadOut~namespace=http://sap.com/xi/BASIS~swcvId=c90d3621a40a11e18645d49f0a4290b1"/>
      </ifw:message>
    </ifw:messages>
    <ifw:matchingInterfaces/>
    <ifw:genericProperties>
      <ifw:swcvinfo>
        <ifw:guid>c90d3621a40a11e18645d49f0a4290b1</ifw:guid>
        <ifw:name>SAP BASIS 7.40</ifw:name>
      </ifw:swcvinfo>
      <ifw:folder>
        <ifw:guid>cb####4#####k##</ifw:guid>
      </ifw:folder>
      <ifw:languages>
        <ifw:language internalCode="EN" original="true"/>
      </ifw:languages>
      <ifw:documentation type="I">
        <name>_ID_978e706090bc380da2e3ddd1c4afa409_ifmmessif</name>
        <namespace>http://sap.com/xi/BASIS</namespace>
      </ifw:documentation>
    </ifw:genericProperties>
  </ifw:properties>
  <wsp:Policy wsu:Id="OP_Check"/>
  <wsp:Policy wsu:Id="OP_Change"/>
  <wsp:Policy wsu:Id="OP_Query"/>
  <wsp:Policy wsu:Id="OP_Create"/>
  <wsp:Policy wsu:Id="OP_Revert"/>
  <wsp:Policy wsu:Id="OP_Read"/>
  <wsp:Policy wsu:Id="OP_Delete"/>
  <wsp:Policy wsu:Id="OP_OpenForEdit"/>
  <wsdl:types>
    <xsd:schema xmlns="http://sap.com/xi/BASIS/Global" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://sap.com/xi/BASIS/Global">
      <xsd:simpleType name="LONG_Description.Content">
        <xsd:restriction base="xsd:string">
          <xsd:maxLength value="255"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="GLOBAL_DateTime">
        <xsd:restriction base="xsd:dateTime">
          <xsd:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(.[0-9]{1,7})?Z"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="LanguageCode">
        <xsd:restriction base="xsd:language">
          <xsd:length value="2"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="LogItemSeverityCode">
        <xsd:restriction base="xsd:token">
          <xsd:length value="1"/>
          <xsd:enumeration value="1"/>
          <xsd:enumeration value="2"/>
          <xsd:enumeration value="3"/>
          <xsd:enumeration value="4"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="LANGUAGEINDEPENDENT_Text">
        <xsd:restriction base="xsd:string"/>
      </xsd:simpleType>
      <xsd:simpleType name="LANGUAGEINDEPENDENT_LONG_Name">
        <xsd:restriction base="xsd:string">
          <xsd:minLength value="0"/>
          <xsd:maxLength value="80"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:complexType name="LONG_Description">
        <xsd:simpleContent>
          <xsd:extension base="LONG_Description.Content">
            <xsd:attribute name="languageCode" type="LanguageCode"/>
          </xsd:extension>
        </xsd:simpleContent>
      </xsd:complexType>
      <xsd:complexType name="Text">
        <xsd:simpleContent>
          <xsd:extension base="xsd:string">
            <xsd:attribute name="languageCode" type="LanguageCode"/>
          </xsd:extension>
        </xsd:simpleContent>
      </xsd:complexType>
    </xsd:schema>
    <xsd:schema xmlns="http://sap.com/xi/BASIS" xmlns:p3="http://sap.com/xi/BASIS/Global" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://sap.com/xi/BASIS">
      <xsd:import namespace="http://sap.com/xi/BASIS/Global"/>
      <xsd:element name="BusinessComponentOpenForEditRequest" type="BusinessComponentDeleteOpenForEditIn"/>
      <xsd:element name="ConfigurationObjectModifyResponse" type="ConfigurationObjectModifyOut"/>
      <xsd:element name="LogMessageCollection" type="LogMessageCollection"/>
      <xsd:element name="BusinessComponentQueryResponse" type="BusinessComponentQueryOut"/>
      <xsd:element name="BusinessComponentDeleteRequest" type="BusinessComponentDeleteOpenForEditIn"/>
      <xsd:element name="BusinessComponentQueryRequest" type="BusinessComponentQueryIn"/>
      <xsd:element name="BusinessComponentCheckRequest" type="BusinessComponentIdentifierCollection"/>
      <xsd:element name="BusinessComponentCreateRequest" type="BusinessComponentCreateChangeIn"/>
      <xsd:element name="BusinessComponentOpenForEditResponse" type="BusinessComponentOpenForEditOut"/>
      <xsd:element name="BusinessComponentChangeRequest" type="BusinessComponentCreateChangeIn"/>
      <xsd:element name="BusinessComponentReadRequest" type="BusinessComponentReadIn"/>
      <xsd:element name="BusinessComponentReadResponse" type="BusinessComponentReadOut"/>
      <xsd:element name="BusinessComponentRevertRequest" type="BusinessComponentIdentifierCollection"/>
      <xsd:simpleType name="CommunicationChannelChannelID">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="60"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="ReadContextCode">
        <xsd:restriction base="xsd:token">
          <xsd:enumeration value="User"/>
          <xsd:enumeration value="Active"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="DesignObjectName">
        <xsd:restriction base="xsd:string">
          <xsd:maxLength value="120"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="LogMessageClassificationCode">
        <xsd:restriction base="xsd:token"/>
      </xsd:simpleType>
      <xsd:simpleType name="IsThirdParty">
        <xsd:restriction base="xsd:boolean"/>
      </xsd:simpleType>
      <xsd:simpleType name="LANGUAGEINDEPENDENT_Text">
        <xsd:restriction base="xsd:string"/>
      </xsd:simpleType>
      <xsd:simpleType name="ValueMappingID">
        <xsd:restriction base="xsd:token">
          <xsd:length value="36"/>
          <xsd:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="SoftwareComponentVersionID">
        <xsd:annotation>
          <xsd:documentation xml:lang="EN">Universally Unique Identifier</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
          <xsd:length value="36"/>
          <xsd:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="CommunicationComponentComponentID">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="60"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="ConfigurationScenarioID">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="60"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="ProcessComponentID">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="60"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="DesignObjectNamespace">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="255"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="CommunicationPartyID">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="60"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="UserID">
        <xsd:annotation>
          <xsd:documentation xml:lang="EN">User Account ID Content</xsd:documentation>
        </xsd:annotation>
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="12"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="CommunicationComponentAdditionalIdentifier.Content">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="60"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="ChangeListChangeListID">
        <xsd:restriction base="xsd:token">
          <xsd:length value="36"/>
          <xsd:pattern value="[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:simpleType name="ReceiverRuleID">
        <xsd:restriction base="xsd:token">
          <xsd:maxLength value="60"/>
        </xsd:restriction>
      </xsd:simpleType>
      <xsd:complexType name="BusinessComponentQueryOut">
        <xsd:sequence>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessComponentID" type="CommunicationComponentID"/>
          <xsd:element minOccurs="0" name="LogMessageCollection" type="LogMessageCollection"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponentQueryIn">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="BusinessComponentID" type="CommunicationComponentID"/>
          <xsd:element minOccurs="0" name="Description" type="p3:LONG_Description"/>
          <xsd:element minOccurs="0" name="AdministrativeData" type="ObjectAdministrativeData"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="ConfigurationObjectModifyOut">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ChangeListID" type="ChangeListID"/>
          <xsd:element minOccurs="0" name="LogMessageCollection" type="LogMessageCollection"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageReceiverRule">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ReceiverRuleID" type="ReceiverRuleID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponentCreateChangeIn">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ChangeListID" type="ChangeListChangeListID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessComponent" type="RestrictedBusinessComponent"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="DesignObjectID">
        <xsd:sequence>
          <xsd:element name="Name" type="DesignObjectName"/>
          <xsd:element name="Namespace" type="DesignObjectNamespace"/>
          <xsd:element minOccurs="0" name="SoftwareComponentVersionID" type="SoftwareComponentVersionID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponentIdentifierCollection">
        <xsd:sequence>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessComponentID" type="CommunicationComponentID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="ChangeListID">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ChangeListID" type="ChangeListChangeListID"/>
          <xsd:element minOccurs="0" name="Name" type="p3:LANGUAGEINDEPENDENT_LONG_Name"/>
          <xsd:element minOccurs="0" name="Description" type="p3:LONG_Description"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageCollection">
        <xsd:sequence>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessage" type="LogMessage"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageChangeList" type="LogMessageChangeList"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageParty" type="LogMessageCommunicationParty"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageProcessComponent" type="LogMessageProcessComponent"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageBusinessSystem" type="LogMessageCommunicationComponent"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageBusinessComponent" type="LogMessageCommunicationComponent"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageIntegrationProcess" type="LogMessageCommunicationComponent"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageCommunicationChannel" type="LogMessageCommunicationChannel"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageSenderAgreement" type="LogMessageMessageHeader"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageReceiverAgreement" type="LogMessageMessageHeader"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageDirectConnection" type="LogMessageMessageHeader"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageIntegratedConfiguration" type="LogMessageMessageHeader"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageReceiverDetermination" type="LogMessageMessageHeader"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageReceiverRule" type="LogMessageReceiverRule"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageInterfaceDetermination" type="LogMessageMessageHeader"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageValueMapping" type="LogMessageValueMapping"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="LogMessageConfigurationScenario" type="LogMessageConfigurationScenario"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="CommunicationComponentAdditionalIdentifier">
        <xsd:simpleContent>
          <xsd:extension base="CommunicationComponentAdditionalIdentifier.Content">
            <xsd:attribute name="schemeID">
              <xsd:simpleType>
                <xsd:restriction base="xsd:token">
                  <xsd:maxLength value="20"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
          </xsd:extension>
        </xsd:simpleContent>
      </xsd:complexType>
      <xsd:complexType name="CommunicationComponentID">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="PartyID" type="CommunicationPartyID"/>
          <xsd:element name="ComponentID" type="CommunicationComponentComponentID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessage">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageCommunicationParty">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="PartyID" type="CommunicationPartyID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageConfigurationScenario">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ConfigurationScenarioID" type="ConfigurationScenarioID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageCommunicationChannel">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="CommunicationChannelID" type="CommunicationChannelID"/>
          <xsd:element name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="RestrictedBusinessComponent">
        <xsd:sequence>
          <xsd:element name="MasterLanguage" type="p3:LanguageCode"/>
          <xsd:element minOccurs="0" name="AdministrativeData" type="RestrictedObjectAdministrativeData"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="Description" type="p3:LONG_Description"/>
          <xsd:element name="BusinessComponentID" type="CommunicationComponentID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="InboundInterface" type="DesignObjectID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="OutboundInterface" type="DesignObjectID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="AdditionalIdentifier" type="CommunicationComponentAdditionalIdentifier"/>
          <xsd:element minOccurs="0" name="IsThirdParty" type="IsThirdParty"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="AssignedUser" type="UserID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="CommunicationChannelID">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="PartyID" type="CommunicationPartyID"/>
          <xsd:element name="ComponentID" type="CommunicationComponentComponentID"/>
          <xsd:element name="ChannelID" type="CommunicationChannelChannelID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageCommunicationComponent">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="CommunicationComponentID" type="CommunicationComponentID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponentReadIn">
        <xsd:sequence>
          <xsd:element default="User" minOccurs="0" name="ReadContext" type="ReadContextCode"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessComponentID" type="CommunicationComponentID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageChangeList">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ChangeListID" type="ChangeListID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="ObjectAdministrativeData">
        <xsd:annotation>
          <xsd:documentation xml:lang="EN">ObjectAdministrativeData</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ResponsibleUserAccountID" type="UserID"/>
          <xsd:element minOccurs="0" name="LastChangeUserAccountID" type="UserID"/>
          <xsd:element minOccurs="0" name="LastChangeDateTime" type="p3:GLOBAL_DateTime"/>
          <xsd:element minOccurs="0" name="FolderPathID" type="p3:LANGUAGEINDEPENDENT_Text"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="RestrictedObjectAdministrativeData">
        <xsd:annotation>
          <xsd:documentation xml:lang="EN">ObjectAdministrativeData</xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ResponsibleUserAccountID" type="UserID"/>
          <xsd:element minOccurs="0" name="FolderPathID" type="LANGUAGEINDEPENDENT_Text"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponentOpenForEditOut">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ChangeListID" type="ChangeListID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessComponent" type="BusinessComponent"/>
          <xsd:element minOccurs="0" name="LogMessageCollection" type="LogMessageCollection"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageItem">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="SeverityCode" type="p3:LogItemSeverityCode"/>
          <xsd:element minOccurs="0" name="ClassificationCode" type="LogMessageClassificationCode"/>
          <xsd:element minOccurs="0" name="Message" type="p3:Text"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponent">
        <xsd:sequence>
          <xsd:element name="MasterLanguage" type="p3:LanguageCode"/>
          <xsd:element minOccurs="0" name="AdministrativeData" type="ObjectAdministrativeData"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="Description" type="p3:LONG_Description"/>
          <xsd:element name="BusinessComponentID" type="CommunicationComponentID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="InboundInterface" type="DesignObjectID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="OutboundInterface" type="DesignObjectID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="AdditionalIdentifier" type="CommunicationComponentAdditionalIdentifier"/>
          <xsd:element minOccurs="0" name="IsThirdParty" type="IsThirdParty"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="AssignedUser" type="UserID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageValueMapping">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ValueMappingID" type="ValueMappingID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponentReadOut">
        <xsd:sequence>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessComponent" type="BusinessComponent"/>
          <xsd:element minOccurs="0" name="LogMessageCollection" type="LogMessageCollection"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageMessageHeader">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="MessageHeader" type="MessageHeaderID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="MessageHeaderID">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="SenderPartyID" type="CommunicationPartyID"/>
          <xsd:element name="SenderComponentID" type="CommunicationComponentComponentID"/>
          <xsd:element name="InterfaceName" type="DesignObjectName"/>
          <xsd:element name="InterfaceNamespace" type="DesignObjectNamespace"/>
          <xsd:element minOccurs="0" name="ReceiverPartyID" type="CommunicationPartyID"/>
          <xsd:element minOccurs="0" name="ReceiverComponentID" type="CommunicationComponentComponentID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="BusinessComponentDeleteOpenForEditIn">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ChangeListID" type="ChangeListChangeListID"/>
          <xsd:element maxOccurs="unbounded" minOccurs="0" name="BusinessComponentID" type="CommunicationComponentID"/>
        </xsd:sequence>
      </xsd:complexType>
      <xsd:complexType name="LogMessageProcessComponent">
        <xsd:sequence>
          <xsd:element minOccurs="0" name="ProcessComponentID" type="ProcessComponentID"/>
          <xsd:element minOccurs="0" name="LogMessageItem" type="LogMessageItem"/>
        </xsd:sequence>
      </xsd:complexType>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="BusinessComponentCheckRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentCheckRequest" name="BusinessComponentCheckRequest"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentChangeRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentChangeRequest" name="BusinessComponentChangeRequest"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentQueryRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentQueryRequest" name="BusinessComponentQueryRequest"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentQueryResponse">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentQueryResponse" name="BusinessComponentQueryResponse"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentCreateRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentCreateRequest" name="BusinessComponentCreateRequest"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentRevertRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentRevertRequest" name="BusinessComponentRevertRequest"/>
  </wsdl:message>
  <wsdl:message name="LogMessageCollection">
    <wsdl:documentation/>
    <wsdl:part element="p1:LogMessageCollection" name="LogMessageCollection"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentReadRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentReadRequest" name="BusinessComponentReadRequest"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentReadResponse">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentReadResponse" name="BusinessComponentReadResponse"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentDeleteRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentDeleteRequest" name="BusinessComponentDeleteRequest"/>
  </wsdl:message>
  <wsdl:message name="ConfigurationObjectModifyResponse">
    <wsdl:documentation/>
    <wsdl:part element="p1:ConfigurationObjectModifyResponse" name="ConfigurationObjectModifyResponse"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentOpenForEditRequest">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentOpenForEditRequest" name="BusinessComponentOpenForEditRequest"/>
  </wsdl:message>
  <wsdl:message name="BusinessComponentOpenForEditResponse">
    <wsdl:documentation/>
    <wsdl:part element="p1:BusinessComponentOpenForEditResponse" name="BusinessComponentOpenForEditResponse"/>
  </wsdl:message>
  <wsdl:portType name="BusinessComponentIn">
    <wsdl:documentation/>
    <wsdl:operation name="Check">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_Check"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentCheckRequest"/>
      <wsdl:output message="p1:LogMessageCollection"/>
    </wsdl:operation>
    <wsdl:operation name="Change">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_Change"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentChangeRequest"/>
      <wsdl:output message="p1:ConfigurationObjectModifyResponse"/>
    </wsdl:operation>
    <wsdl:operation name="Query">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_Query"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentQueryRequest"/>
      <wsdl:output message="p1:BusinessComponentQueryResponse"/>
    </wsdl:operation>
    <wsdl:operation name="Create">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_Create"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentCreateRequest"/>
      <wsdl:output message="p1:ConfigurationObjectModifyResponse"/>
    </wsdl:operation>
    <wsdl:operation name="Revert">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_Revert"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentRevertRequest"/>
      <wsdl:output message="p1:LogMessageCollection"/>
    </wsdl:operation>
    <wsdl:operation name="Read">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_Read"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentReadRequest"/>
      <wsdl:output message="p1:BusinessComponentReadResponse"/>
    </wsdl:operation>
    <wsdl:operation name="Delete">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_Delete"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentDeleteRequest"/>
      <wsdl:output message="p1:ConfigurationObjectModifyResponse"/>
    </wsdl:operation>
    <wsdl:operation name="OpenForEdit">
      <wsdl:documentation/>
      <wsp:Policy>
        <wsp:PolicyReference URI="#OP_OpenForEdit"/>
      </wsp:Policy>
      <wsdl:input message="p1:BusinessComponentOpenForEditRequest"/>
      <wsdl:output message="p1:BusinessComponentOpenForEditResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="BusinessComponentInBinding" type="p1:BusinessComponentIn">
    <soap:binding xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Check">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Change">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Query">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Create">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Revert">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Read">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="Delete">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    <wsdl:operation name="OpenForEdit">
      <soap:operation xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" soapAction="http://sap.com/xi/WebService/soap1.1"/>
      <wsdl:input>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
<wsdl:service name="BusinessComponentIn_Service">
<wsdl:port xmlns:bprf="http://sap.com/xi/BASIS" binding="bprf:BusinessComponentInBinding" name="BusinessComponentIn_Port">
<soap:address location="/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>
