package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "BusinessSystemIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface BusinessSystemIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "BusinessSystemCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemCheckRequest") com.sap.xi.basis.BusinessSystemIdentifierCollection businessSystemCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "BusinessSystemChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemChangeRequest") com.sap.xi.basis.BusinessSystemCreateChangeIn businessSystemChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "BusinessSystemQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemQueryResponse")
  public com.sap.xi.basis.BusinessSystemQueryOut query(@javax.jws.WebParam(name = "BusinessSystemQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemQueryRequest") com.sap.xi.basis.BusinessSystemQueryIn businessSystemQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "BusinessSystemCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemCreateRequest") com.sap.xi.basis.BusinessSystemCreateChangeIn businessSystemCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "BusinessSystemRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemRevertRequest") com.sap.xi.basis.BusinessSystemIdentifierCollection businessSystemRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "BusinessSystemReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemReadResponse")
  public com.sap.xi.basis.BusinessSystemReadOut read(@javax.jws.WebParam(name = "BusinessSystemReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemReadRequest") com.sap.xi.basis.BusinessSystemReadIn businessSystemReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "BusinessSystemDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemDeleteRequest") com.sap.xi.basis.BusinessSystemDeleteOpenForEditIn businessSystemDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "BusinessSystemOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemOpenForEditResponse")
  public com.sap.xi.basis.BusinessSystemOpenForEditOut openForEdit(@javax.jws.WebParam(name = "BusinessSystemOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "BusinessSystemOpenForEditRequest") com.sap.xi.basis.BusinessSystemDeleteOpenForEditIn businessSystemOpenForEditRequest);

}
