package com.sap.xi.basis;

/**
 * Service implementation of {BusinessComponentIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "BusinessComponentIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/BusinessComponentIn/BusinessComponentIn.wsdl")
public class BusinessComponentInService extends javax.xml.ws.Service {

  private final static java.net.URL BUSINESSCOMPONENTINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = BusinessComponentInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/BusinessComponentIn/BusinessComponentIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    BUSINESSCOMPONENTINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public BusinessComponentInService() throws java.net.MalformedURLException {
    super(BUSINESSCOMPONENTINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "BusinessComponentIn_Service"));
  }
  public BusinessComponentInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [BusinessComponentIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "BusinessComponentIn_Port")
  public com.sap.xi.basis.BusinessComponentIn getBusinessComponentIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","BusinessComponentIn_Port");
    return (com.sap.xi.basis.BusinessComponentIn) super.getPort(portName,com.sap.xi.basis.BusinessComponentIn.class);
  }
}
