package com.sap.xi.basis;

/**
 * Service implementation of {BusinessSystemIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "BusinessSystemIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/BusinessSystemIn/BusinessSystemIn.wsdl")
public class BusinessSystemInService extends javax.xml.ws.Service {

  private final static java.net.URL BUSINESSSYSTEMINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = BusinessSystemInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/BusinessSystemIn/BusinessSystemIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    BUSINESSSYSTEMINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public BusinessSystemInService() throws java.net.MalformedURLException {
    super(BUSINESSSYSTEMINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "BusinessSystemIn_Service"));
  }
  public BusinessSystemInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [BusinessSystemIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "BusinessSystemIn_Port")
  public com.sap.xi.basis.BusinessSystemIn getBusinessSystemIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","BusinessSystemIn_Port");
    return (com.sap.xi.basis.BusinessSystemIn) super.getPort(portName,com.sap.xi.basis.BusinessSystemIn.class);
  }
}
