package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "CommunicationChannelIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface CommunicationChannelIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "CommunicationChannelCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelCheckRequest") com.sap.xi.basis.CommunicationChannelIdentifierCollection communicationChannelCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "CommunicationChannelChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelChangeRequest") com.sap.xi.basis.CommunicationChannelCreateChangeIn communicationChannelChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "CommunicationChannelQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelQueryResponse")
  public com.sap.xi.basis.CommunicationChannelQueryOut query(@javax.jws.WebParam(name = "CommunicationChannelQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelQueryRequest") com.sap.xi.basis.CommunicationChannelQueryIn communicationChannelQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "CommunicationChannelCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelCreateRequest") com.sap.xi.basis.CommunicationChannelCreateChangeIn communicationChannelCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "CommunicationChannelRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelRevertRequest") com.sap.xi.basis.CommunicationChannelIdentifierCollection communicationChannelRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "CommunicationChannelReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelReadResponse")
  public com.sap.xi.basis.CommunicationChannelReadOut read(@javax.jws.WebParam(name = "CommunicationChannelReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelReadRequest") com.sap.xi.basis.CommunicationChannelReadIn communicationChannelReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "CommunicationChannelDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelDeleteRequest") com.sap.xi.basis.CommunicationChannelDeleteOpenForEditIn communicationChannelDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "CommunicationChannelOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelOpenForEditResponse")
  public com.sap.xi.basis.CommunicationChannelOpenForEditOut openForEdit(@javax.jws.WebParam(name = "CommunicationChannelOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelOpenForEditRequest") com.sap.xi.basis.CommunicationChannelDeleteOpenForEditIn communicationChannelOpenForEditRequest);

  /**
   * Java representation of web method [CreateFromTemplate].
   */
  @javax.jws.WebMethod(operationName = "CreateFromTemplate", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut createFromTemplate(@javax.jws.WebParam(name = "CommunicationChannelCreateFromTemplateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationChannelCreateFromTemplateRequest") com.sap.xi.basis.CommunicationChannelCreateFromTemplateIn communicationChannelCreateFromTemplateRequest);

}
