package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "CommunicationPartyIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface CommunicationPartyIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "CommunicationPartyCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyCheckRequest") com.sap.xi.basis.CommunicationPartyIdentifierCollection communicationPartyCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "CommunicationPartyChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyChangeRequest") com.sap.xi.basis.CommunicationPartyCreateChangeIn communicationPartyChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "CommunicationPartyQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyQueryResponse")
  public com.sap.xi.basis.CommunicationPartyQueryOut query(@javax.jws.WebParam(name = "CommunicationPartyQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyQueryRequest") com.sap.xi.basis.CommunicationPartyQueryIn communicationPartyQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "CommunicationPartyCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyCreateRequest") com.sap.xi.basis.CommunicationPartyCreateChangeIn communicationPartyCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "CommunicationPartyRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyRevertRequest") com.sap.xi.basis.CommunicationPartyIdentifierCollection communicationPartyRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "CommunicationPartyReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyReadResponse")
  public com.sap.xi.basis.CommunicationPartyReadOut read(@javax.jws.WebParam(name = "CommunicationPartyReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyReadRequest") com.sap.xi.basis.CommunicationPartyReadIn communicationPartyReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "CommunicationPartyDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyDeleteRequest") com.sap.xi.basis.CommunicationPartyDeleteOpenForEditIn communicationPartyDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "CommunicationPartyOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyOpenForEditResponse")
  public com.sap.xi.basis.CommunicationPartyOpenForEditOut openForEdit(@javax.jws.WebParam(name = "CommunicationPartyOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "CommunicationPartyOpenForEditRequest") com.sap.xi.basis.CommunicationPartyDeleteOpenForEditIn communicationPartyOpenForEditRequest);

}
