package com.sap.xi.basis;

/**
 * Service implementation of {ConfigurationScenarioIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ConfigurationScenarioIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/ConfigurationScenarioIn/ConfigurationScenarioIn.wsdl")
public class ConfigurationScenarioInService extends javax.xml.ws.Service {

  private final static java.net.URL CONFIGURATIONSCENARIOINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = ConfigurationScenarioInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/ConfigurationScenarioIn/ConfigurationScenarioIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    CONFIGURATIONSCENARIOINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public ConfigurationScenarioInService() throws java.net.MalformedURLException {
    super(CONFIGURATIONSCENARIOINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "ConfigurationScenarioIn_Service"));
  }
  public ConfigurationScenarioInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ConfigurationScenarioIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "ConfigurationScenarioIn_Port")
  public com.sap.xi.basis.ConfigurationScenarioIn getConfigurationScenarioIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","ConfigurationScenarioIn_Port");
    return (com.sap.xi.basis.ConfigurationScenarioIn) super.getPort(portName,com.sap.xi.basis.ConfigurationScenarioIn.class);
  }
}
