package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "ConfigurationScenarioIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface ConfigurationScenarioIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "ConfigurationScenarioCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioCheckRequest") com.sap.xi.basis.ConfigurationScenarioIdentifierCollection configurationScenarioCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "ConfigurationScenarioChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioChangeRequest") com.sap.xi.basis.ConfigurationScenarioCreateChangeIn configurationScenarioChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationScenarioQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioQueryResponse")
  public com.sap.xi.basis.ConfigurationScenarioQueryOut query(@javax.jws.WebParam(name = "ConfigurationScenarioQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioQueryRequest") com.sap.xi.basis.ConfigurationScenarioQueryIn configurationScenarioQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "ConfigurationScenarioCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioCreateRequest") com.sap.xi.basis.ConfigurationScenarioCreateChangeIn configurationScenarioCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "ConfigurationScenarioRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioRevertRequest") com.sap.xi.basis.ConfigurationScenarioIdentifierCollection configurationScenarioRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationScenarioReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioReadResponse")
  public com.sap.xi.basis.ConfigurationScenarioReadOut read(@javax.jws.WebParam(name = "ConfigurationScenarioReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioReadRequest") com.sap.xi.basis.ConfigurationScenarioReadIn configurationScenarioReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "ConfigurationScenarioDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioDeleteRequest") com.sap.xi.basis.ConfigurationScenarioDeleteOpenForEditIn configurationScenarioDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationScenarioOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioOpenForEditResponse")
  public com.sap.xi.basis.ConfigurationScenarioOpenForEditOut openForEdit(@javax.jws.WebParam(name = "ConfigurationScenarioOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationScenarioOpenForEditRequest") com.sap.xi.basis.ConfigurationScenarioDeleteOpenForEditIn configurationScenarioOpenForEditRequest);

}
