package com.sap.xi.basis;

/**
 * Service implementation of {DirectConnectionIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "DirectConnectionIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/DirectConnectionIn/DirectConnectionIn.wsdl")
public class DirectConnectionInService extends javax.xml.ws.Service {

  private final static java.net.URL DIRECTCONNECTIONINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = DirectConnectionInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/DirectConnectionIn/DirectConnectionIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    DIRECTCONNECTIONINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public DirectConnectionInService() throws java.net.MalformedURLException {
    super(DIRECTCONNECTIONINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "DirectConnectionIn_Service"));
  }
  public DirectConnectionInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [DirectConnectionIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "DirectConnectionIn_Port")
  public com.sap.xi.basis.DirectConnectionIn getDirectConnectionIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","DirectConnectionIn_Port");
    return (com.sap.xi.basis.DirectConnectionIn) super.getPort(portName,com.sap.xi.basis.DirectConnectionIn.class);
  }
}
