package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "DirectConnectionIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface DirectConnectionIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "DirectConnectionCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionCheckRequest") com.sap.xi.basis.DirectConnectionIdentifierCollection directConnectionCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "DirectConnectionChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionChangeRequest") com.sap.xi.basis.DirectConnectionCreateChangeIn directConnectionChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "DirectConnectionQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionQueryResponse")
  public com.sap.xi.basis.DirectConnectionQueryOut query(@javax.jws.WebParam(name = "DirectConnectionQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionQueryRequest") com.sap.xi.basis.DirectConnectionQueryIn directConnectionQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "DirectConnectionCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionCreateRequest") com.sap.xi.basis.DirectConnectionCreateChangeIn directConnectionCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "DirectConnectionRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionRevertRequest") com.sap.xi.basis.DirectConnectionIdentifierCollection directConnectionRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "DirectConnectionReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionReadResponse")
  public com.sap.xi.basis.DirectConnectionReadOut read(@javax.jws.WebParam(name = "DirectConnectionReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionReadRequest") com.sap.xi.basis.DirectConnectionReadIn directConnectionReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "DirectConnectionDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionDeleteRequest") com.sap.xi.basis.DirectConnectionDeleteOpenForEditIn directConnectionDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "DirectConnectionOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionOpenForEditResponse")
  public com.sap.xi.basis.DirectConnectionOpenForEditOut openForEdit(@javax.jws.WebParam(name = "DirectConnectionOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "DirectConnectionOpenForEditRequest") com.sap.xi.basis.DirectConnectionDeleteOpenForEditIn directConnectionOpenForEditRequest);

}
