package com.sap.xi.basis;

/**
 * Service implementation of {IntegratedConfigurationIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "IntegratedConfigurationIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/IntegratedConfigurationIn/IntegratedConfigurationIn.wsdl")
public class IntegratedConfigurationInService extends javax.xml.ws.Service {

  private final static java.net.URL INTEGRATEDCONFIGURATIONINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = IntegratedConfigurationInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/IntegratedConfigurationIn/IntegratedConfigurationIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    INTEGRATEDCONFIGURATIONINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public IntegratedConfigurationInService() throws java.net.MalformedURLException {
    super(INTEGRATEDCONFIGURATIONINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "IntegratedConfigurationIn_Service"));
  }
  public IntegratedConfigurationInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [IntegratedConfigurationIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "IntegratedConfigurationIn_Port")
  public com.sap.xi.basis.IntegratedConfigurationIn getIntegratedConfigurationIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","IntegratedConfigurationIn_Port");
    return (com.sap.xi.basis.IntegratedConfigurationIn) super.getPort(portName,com.sap.xi.basis.IntegratedConfigurationIn.class);
  }
}
