package com.sap.xi.basis;

/**
 * Service implementation of {InterfaceDeterminationIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "InterfaceDeterminationIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/InterfaceDeterminationIn/InterfaceDeterminationIn.wsdl")
public class InterfaceDeterminationInService extends javax.xml.ws.Service {

  private final static java.net.URL INTERFACEDETERMINATIONINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = InterfaceDeterminationInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/InterfaceDeterminationIn/InterfaceDeterminationIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    INTERFACEDETERMINATIONINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public InterfaceDeterminationInService() throws java.net.MalformedURLException {
    super(INTERFACEDETERMINATIONINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "InterfaceDeterminationIn_Service"));
  }
  public InterfaceDeterminationInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [InterfaceDeterminationIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "InterfaceDeterminationIn_Port")
  public com.sap.xi.basis.InterfaceDeterminationIn getInterfaceDeterminationIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","InterfaceDeterminationIn_Port");
    return (com.sap.xi.basis.InterfaceDeterminationIn) super.getPort(portName,com.sap.xi.basis.InterfaceDeterminationIn.class);
  }
}
