package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "InterfaceDeterminationIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface InterfaceDeterminationIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "InterfaceDeterminationCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationCheckRequest") com.sap.xi.basis.InterfaceDeterminationIdentifierCollection interfaceDeterminationCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "InterfaceDeterminationChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationChangeRequest") com.sap.xi.basis.InterfaceDeterminationCreateChangeIn interfaceDeterminationChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "InterfaceDeterminationQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationQueryResponse")
  public com.sap.xi.basis.InterfaceDeterminationQueryOut query(@javax.jws.WebParam(name = "InterfaceDeterminationQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationQueryRequest") com.sap.xi.basis.InterfaceDeterminationQueryIn interfaceDeterminationQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "InterfaceDeterminationCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationCreateRequest") com.sap.xi.basis.InterfaceDeterminationCreateChangeIn interfaceDeterminationCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "InterfaceDeterminationRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationRevertRequest") com.sap.xi.basis.InterfaceDeterminationIdentifierCollection interfaceDeterminationRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "InterfaceDeterminationReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationReadResponse")
  public com.sap.xi.basis.InterfaceDeterminationReadOut read(@javax.jws.WebParam(name = "InterfaceDeterminationReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationReadRequest") com.sap.xi.basis.InterfaceDeterminationReadIn interfaceDeterminationReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "InterfaceDeterminationDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationDeleteRequest") com.sap.xi.basis.InterfaceDeterminationDeleteOpenForEditIn interfaceDeterminationDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "InterfaceDeterminationOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationOpenForEditResponse")
  public com.sap.xi.basis.InterfaceDeterminationOpenForEditOut openForEdit(@javax.jws.WebParam(name = "InterfaceDeterminationOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "InterfaceDeterminationOpenForEditRequest") com.sap.xi.basis.InterfaceDeterminationDeleteOpenForEditIn interfaceDeterminationOpenForEditRequest);

}
