package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "IntegratedConfigurationIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface IntegratedConfigurationIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "IntegratedConfigurationCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationCheckRequest") com.sap.xi.basis.IntegratedConfigurationIdentifierCollection integratedConfigurationCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "IntegratedConfigurationChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationChangeRequest") com.sap.xi.basis.IntegratedConfigurationCreateChangeIn integratedConfigurationChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "IntegratedConfigurationQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationQueryResponse")
  public com.sap.xi.basis.IntegratedConfigurationQueryOut query(@javax.jws.WebParam(name = "IntegratedConfigurationQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationQueryRequest") com.sap.xi.basis.IntegratedConfigurationQueryIn integratedConfigurationQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "IntegratedConfigurationCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationCreateRequest") com.sap.xi.basis.IntegratedConfigurationCreateChangeIn integratedConfigurationCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "IntegratedConfigurationRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationRevertRequest") com.sap.xi.basis.IntegratedConfigurationIdentifierCollection integratedConfigurationRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "IntegratedConfigurationReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationReadResponse")
  public com.sap.xi.basis.IntegratedConfigurationReadOut read(@javax.jws.WebParam(name = "IntegratedConfigurationReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationReadRequest") com.sap.xi.basis.IntegratedConfigurationReadIn integratedConfigurationReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "IntegratedConfigurationDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationDeleteRequest") com.sap.xi.basis.IntegratedConfigurationDeleteOpenForEditIn integratedConfigurationDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "IntegratedConfigurationOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationOpenForEditResponse")
  public com.sap.xi.basis.IntegratedConfigurationOpenForEditOut openForEdit(@javax.jws.WebParam(name = "IntegratedConfigurationOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "IntegratedConfigurationOpenForEditRequest") com.sap.xi.basis.IntegratedConfigurationDeleteOpenForEditIn integratedConfigurationOpenForEditRequest);

}
