package com.sap.xi.basis;

/**
 * Service implementation of {IntegrationProcessIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "IntegrationProcessIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/IntegrationProcessIn/IntegrationProcessIn.wsdl")
public class IntegrationProcessInService extends javax.xml.ws.Service {

  private final static java.net.URL INTEGRATIONPROCESSINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = IntegrationProcessInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/IntegrationProcessIn/IntegrationProcessIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    INTEGRATIONPROCESSINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public IntegrationProcessInService() throws java.net.MalformedURLException {
    super(INTEGRATIONPROCESSINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "IntegrationProcessIn_Service"));
  }
  public IntegrationProcessInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [IntegrationProcessIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "IntegrationProcessIn_Port")
  public com.sap.xi.basis.IntegrationProcessIn getIntegrationProcessIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","IntegrationProcessIn_Port");
    return (com.sap.xi.basis.IntegrationProcessIn) super.getPort(portName,com.sap.xi.basis.IntegrationProcessIn.class);
  }
}
