package com.sap.xi.basis;

/**
 * Service implementation of {ProcessComponentIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ProcessComponentIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/ProcessComponentIn/ProcessComponentIn.wsdl")
public class ProcessComponentInService extends javax.xml.ws.Service {

  private final static java.net.URL PROCESSCOMPONENTINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = ProcessComponentInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/ProcessComponentIn/ProcessComponentIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    PROCESSCOMPONENTINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public ProcessComponentInService() throws java.net.MalformedURLException {
    super(PROCESSCOMPONENTINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "ProcessComponentIn_Service"));
  }
  public ProcessComponentInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ProcessComponentIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "ProcessComponentIn_Port")
  public com.sap.xi.basis.ProcessComponentIn getProcessComponentIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","ProcessComponentIn_Port");
    return (com.sap.xi.basis.ProcessComponentIn) super.getPort(portName,com.sap.xi.basis.ProcessComponentIn.class);
  }
}
