package com.sap.xi.basis;

/**
 * Service implementation of {ReceiverAgreementIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ReceiverAgreementIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/ReceiverAgreementIn/ReceiverAgreementIn.wsdl")
public class ReceiverAgreementInService extends javax.xml.ws.Service {

  private final static java.net.URL RECEIVERAGREEMENTINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = ReceiverAgreementInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/ReceiverAgreementIn/ReceiverAgreementIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    RECEIVERAGREEMENTINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public ReceiverAgreementInService() throws java.net.MalformedURLException {
    super(RECEIVERAGREEMENTINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "ReceiverAgreementIn_Service"));
  }
  public ReceiverAgreementInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ReceiverAgreementIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "ReceiverAgreementIn_Port")
  public com.sap.xi.basis.ReceiverAgreementIn getReceiverAgreementIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","ReceiverAgreementIn_Port");
    return (com.sap.xi.basis.ReceiverAgreementIn) super.getPort(portName,com.sap.xi.basis.ReceiverAgreementIn.class);
  }
}
