package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "ReceiverRuleIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface ReceiverRuleIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "ReceiverRuleCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleCheckRequest") com.sap.xi.basis.ReceiverRuleIdentifierCollection receiverRuleCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "ReceiverRuleChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleChangeRequest") com.sap.xi.basis.ReceiverRuleCreateChangeIn receiverRuleChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ReceiverRuleQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleQueryResponse")
  public com.sap.xi.basis.ReceiverRuleQueryOut query(@javax.jws.WebParam(name = "ReceiverRuleQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleQueryRequest") com.sap.xi.basis.ReceiverRuleQueryIn receiverRuleQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "ReceiverRuleCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleCreateRequest") com.sap.xi.basis.ReceiverRuleCreateChangeIn receiverRuleCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "ReceiverRuleRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleRevertRequest") com.sap.xi.basis.ReceiverRuleIdentifierCollection receiverRuleRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ReceiverRuleReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleReadResponse")
  public com.sap.xi.basis.ReceiverRuleReadOut read(@javax.jws.WebParam(name = "ReceiverRuleReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleReadRequest") com.sap.xi.basis.ReceiverRuleReadIn receiverRuleReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "ReceiverRuleDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleDeleteRequest") com.sap.xi.basis.ReceiverRuleDeleteOpenForEditIn receiverRuleDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ReceiverRuleOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleOpenForEditResponse")
  public com.sap.xi.basis.ReceiverRuleOpenForEditOut openForEdit(@javax.jws.WebParam(name = "ReceiverRuleOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverRuleOpenForEditRequest") com.sap.xi.basis.ReceiverRuleDeleteOpenForEditIn receiverRuleOpenForEditRequest);

}
