package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "ReceiverAgreementIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface ReceiverAgreementIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "ReceiverAgreementCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementCheckRequest") com.sap.xi.basis.ReceiverAgreementIdentifierCollection receiverAgreementCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "ReceiverAgreementChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementChangeRequest") com.sap.xi.basis.ReceiverAgreementCreateChangeIn receiverAgreementChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ReceiverAgreementQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementQueryResponse")
  public com.sap.xi.basis.ReceiverAgreementQueryOut query(@javax.jws.WebParam(name = "ReceiverAgreementQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementQueryRequest") com.sap.xi.basis.ReceiverAgreementQueryIn receiverAgreementQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "ReceiverAgreementCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementCreateRequest") com.sap.xi.basis.ReceiverAgreementCreateChangeIn receiverAgreementCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "ReceiverAgreementRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementRevertRequest") com.sap.xi.basis.ReceiverAgreementIdentifierCollection receiverAgreementRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ReceiverAgreementReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementReadResponse")
  public com.sap.xi.basis.ReceiverAgreementReadOut read(@javax.jws.WebParam(name = "ReceiverAgreementReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementReadRequest") com.sap.xi.basis.ReceiverAgreementReadIn receiverAgreementReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "ReceiverAgreementDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementDeleteRequest") com.sap.xi.basis.ReceiverAgreementDeleteOpenForEditIn receiverAgreementDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ReceiverAgreementOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementOpenForEditResponse")
  public com.sap.xi.basis.ReceiverAgreementOpenForEditOut openForEdit(@javax.jws.WebParam(name = "ReceiverAgreementOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ReceiverAgreementOpenForEditRequest") com.sap.xi.basis.ReceiverAgreementDeleteOpenForEditIn receiverAgreementOpenForEditRequest);

}
