package com.sap.xi.basis;

/**
 * Service implementation of {ReceiverRuleIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ReceiverRuleIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/ReceiverRuleIn/ReceiverRuleIn.wsdl")
public class ReceiverRuleInService extends javax.xml.ws.Service {

  private final static java.net.URL RECEIVERRULEINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = ReceiverRuleInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/ReceiverRuleIn/ReceiverRuleIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    RECEIVERRULEINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public ReceiverRuleInService() throws java.net.MalformedURLException {
    super(RECEIVERRULEINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "ReceiverRuleIn_Service"));
  }
  public ReceiverRuleInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ReceiverRuleIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "ReceiverRuleIn_Port")
  public com.sap.xi.basis.ReceiverRuleIn getReceiverRuleIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","ReceiverRuleIn_Port");
    return (com.sap.xi.basis.ReceiverRuleIn) super.getPort(portName,com.sap.xi.basis.ReceiverRuleIn.class);
  }
}
