package com.sap.xi.basis;

/**
 * Service implementation of {ReceiverDeterminationIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ReceiverDeterminationIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/ReceiverDeterminationIn/ReceiverDeterminationIn.wsdl")
public class ReceiverDeterminationInService extends javax.xml.ws.Service {

  private final static java.net.URL RECEIVERDETERMINATIONINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = ReceiverDeterminationInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/ReceiverDeterminationIn/ReceiverDeterminationIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    RECEIVERDETERMINATIONINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public ReceiverDeterminationInService() throws java.net.MalformedURLException {
    super(RECEIVERDETERMINATIONINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "ReceiverDeterminationIn_Service"));
  }
  public ReceiverDeterminationInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ReceiverDeterminationIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "ReceiverDeterminationIn_Port")
  public com.sap.xi.basis.ReceiverDeterminationIn getReceiverDeterminationIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","ReceiverDeterminationIn_Port");
    return (com.sap.xi.basis.ReceiverDeterminationIn) super.getPort(portName,com.sap.xi.basis.ReceiverDeterminationIn.class);
  }
}
