package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "SenderAgreementIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface SenderAgreementIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "SenderAgreementCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementCheckRequest") com.sap.xi.basis.SenderAgreementIdentifierCollection senderAgreementCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "SenderAgreementChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementChangeRequest") com.sap.xi.basis.SenderAgreementCreateChangeIn senderAgreementChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "SenderAgreementQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementQueryResponse")
  public com.sap.xi.basis.SenderAgreementQueryOut query(@javax.jws.WebParam(name = "SenderAgreementQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementQueryRequest") com.sap.xi.basis.SenderAgreementQueryIn senderAgreementQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "SenderAgreementCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementCreateRequest") com.sap.xi.basis.SenderAgreementCreateChangeIn senderAgreementCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "SenderAgreementRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementRevertRequest") com.sap.xi.basis.SenderAgreementIdentifierCollection senderAgreementRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "SenderAgreementReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementReadResponse")
  public com.sap.xi.basis.SenderAgreementReadOut read(@javax.jws.WebParam(name = "SenderAgreementReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementReadRequest") com.sap.xi.basis.SenderAgreementReadIn senderAgreementReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "SenderAgreementDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementDeleteRequest") com.sap.xi.basis.SenderAgreementDeleteOpenForEditIn senderAgreementDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "SenderAgreementOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementOpenForEditResponse")
  public com.sap.xi.basis.SenderAgreementOpenForEditOut openForEdit(@javax.jws.WebParam(name = "SenderAgreementOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "SenderAgreementOpenForEditRequest") com.sap.xi.basis.SenderAgreementDeleteOpenForEditIn senderAgreementOpenForEditRequest);

}
