package com.sap.xi.basis;

/**
 * Service implementation of {ValueMappingIn_Service} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "ValueMappingIn_Service", targetNamespace = "http://sap.com/xi/BASIS", wsdlLocation = "wsdl/com/sap/xi/basis/ValueMappingIn/ValueMappingIn.wsdl")
public class ValueMappingInService extends javax.xml.ws.Service {

  private final static java.net.URL VALUEMAPPINGINSERVICE_WSDL_LOCATION;
  static {
    java.net.URL url = null;
    try {
		java.net.URL tmpUrl = ValueMappingInService.class.getClassLoader().getResource("wsdl/com/sap/xi/basis/ValueMappingIn/ValueMappingIn.wsdl");
		url = new java.net.URL(tmpUrl.getProtocol(), tmpUrl.getHost(), tmpUrl.getPort(), tmpUrl.getFile());
    } catch (java.net.MalformedURLException e) {
      e.printStackTrace();
    }
    VALUEMAPPINGINSERVICE_WSDL_LOCATION = url;
  }
  /**
   * Default service constructor.
   */
  public ValueMappingInService() throws java.net.MalformedURLException {
    super(VALUEMAPPINGINSERVICE_WSDL_LOCATION, new javax.xml.namespace.QName("http://sap.com/xi/BASIS", "ValueMappingIn_Service"));
  }
  public ValueMappingInService(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [ValueMappingIn_Port].
   */
  @javax.xml.ws.WebEndpoint(name = "ValueMappingIn_Port")
  public com.sap.xi.basis.ValueMappingIn getValueMappingIn_Port() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("http://sap.com/xi/BASIS","ValueMappingIn_Port");
    return (com.sap.xi.basis.ValueMappingIn) super.getPort(portName,com.sap.xi.basis.ValueMappingIn.class);
  }
}
