package com.sap.xi.basis;

/**
 * Service Endpoint Interface (generated by SAP WSDL to Java generator).
 */
@javax.jws.WebService(name = "ValueMappingIn", targetNamespace = "http://sap.com/xi/BASIS")
@javax.jws.soap.SOAPBinding(parameterStyle = javax.jws.soap.SOAPBinding.ParameterStyle.BARE, style = javax.jws.soap.SOAPBinding.Style.DOCUMENT, use = javax.jws.soap.SOAPBinding.Use.LITERAL)
public interface ValueMappingIn {

  /**
   * Java representation of web method [Check].
   */
  @javax.jws.WebMethod(operationName = "Check", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection check(@javax.jws.WebParam(name = "ValueMappingCheckRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingCheckRequest") com.sap.xi.basis.ValueMappingIdentifierCollection valueMappingCheckRequest);

  /**
   * Java representation of web method [Change].
   */
  @javax.jws.WebMethod(operationName = "Change", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut change(@javax.jws.WebParam(name = "ValueMappingChangeRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingChangeRequest") com.sap.xi.basis.ValueMappingCreateChangeIn valueMappingChangeRequest);

  /**
   * Java representation of web method [Query].
   */
  @javax.jws.WebMethod(operationName = "Query", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ValueMappingQueryResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingQueryResponse")
  public com.sap.xi.basis.ValueMappingQueryOut query(@javax.jws.WebParam(name = "ValueMappingQueryRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingQueryRequest") com.sap.xi.basis.ValueMappingQueryIn valueMappingQueryRequest);

  /**
   * Java representation of web method [Create].
   */
  @javax.jws.WebMethod(operationName = "Create", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut create(@javax.jws.WebParam(name = "ValueMappingCreateRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingCreateRequest") com.sap.xi.basis.ValueMappingCreateChangeIn valueMappingCreateRequest);

  /**
   * Java representation of web method [Revert].
   */
  @javax.jws.WebMethod(operationName = "Revert", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "LogMessageCollection", targetNamespace = "http://sap.com/xi/BASIS", partName = "LogMessageCollection")
  public com.sap.xi.basis.LogMessageCollection revert(@javax.jws.WebParam(name = "ValueMappingRevertRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingRevertRequest") com.sap.xi.basis.ValueMappingIdentifierCollection valueMappingRevertRequest);

  /**
   * Java representation of web method [Read].
   */
  @javax.jws.WebMethod(operationName = "Read", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ValueMappingReadResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingReadResponse")
  public com.sap.xi.basis.ValueMappingReadOut read(@javax.jws.WebParam(name = "ValueMappingReadRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingReadRequest") com.sap.xi.basis.ValueMappingReadIn valueMappingReadRequest);

  /**
   * Java representation of web method [Delete].
   */
  @javax.jws.WebMethod(operationName = "Delete", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ConfigurationObjectModifyResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ConfigurationObjectModifyResponse")
  public com.sap.xi.basis.ConfigurationObjectModifyOut delete(@javax.jws.WebParam(name = "ValueMappingDeleteRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingDeleteRequest") com.sap.xi.basis.ValueMappingDeleteOpenForEditIn valueMappingDeleteRequest);

  /**
   * Java representation of web method [OpenForEdit].
   */
  @javax.jws.WebMethod(operationName = "OpenForEdit", action = "http://sap.com/xi/WebService/soap1.1")
  @javax.jws.WebResult(name = "ValueMappingOpenForEditResponse", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingOpenForEditResponse")
  public com.sap.xi.basis.ValueMappingOpenForEditOut openForEdit(@javax.jws.WebParam(name = "ValueMappingOpenForEditRequest", targetNamespace = "http://sap.com/xi/BASIS", partName = "ValueMappingOpenForEditRequest") com.sap.xi.basis.ValueMappingDeleteOpenForEditIn valueMappingOpenForEditRequest);

}
